baseurl = "/"
languageCode = "en-us"
title = "BLUE JEAN BLUES"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "this isa my description"
  cover = "images/cover.png"
  author = "TiâuÛi Lâu"
  authorlocation = "Taipei, Taiwan"
  authorwebsite = "https://tiauweed.netlify.com/post/just-another-test-post/"
  bio= "Taiwan independence movement, MetalHead, Denim addicted."
  logo = "images/logo.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..."
  githubName = "watain666"
  twitterName = "tiauweed"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "tiauweed"
